### ISSUE TITLE
Convert AUEN to use non static Domain class

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-automated-upcoming-event-notifications#2] opened 2018-04-25 15:47 UTC
Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11234

See what was done for waitlist in [#11138](https://events.codebasehq.com/projects/event-espresso/tickets/11138) - Convert Domain class to use non-static DomainBase, and avoid other uses of static where possible

@sethshoultes this should probably get in my queue if you want to keep the auen add-on up to date on pr.

Also the AUEN add-on itself has been up for testing with the latest changes since Nov 23. I don't know if there's been any action on it but the changes are in master so if this ticket is prioritized so the pr channel can get updated, then the pr channel will receive all the latest (possibly untested by people other than myself and automated tests) work as well.

**Comment by sethshoultes** [comment] 2018-04-25 15:47
Update this topic when this add-on's beta release is updated:

https://eventespresso.com/topic/automated-upcoming-event-notification-fails-to-activate/

**Comment by nerrad** [comment] 2018-04-25 15:50
This is a duplicate of #1 closing.

**Comment by nerrad** [comment] 2018-04-25 15:51
looks like I may have to modify the duplicate detector to also check for duplicates in pull requests.  It probably assumes to only check duplicates across issues.

**Closed by nerrad** 2018-04-25 15:50 UTC
Labels: triage

**Comment by sethshoultes** [comment] 2018-04-25 16:16
Oh, I didn't see or remember the pull request.
